const crimeTypeOptions = [
    { value: '110', label: 'Homicide' },
    { value: '113', label: 'Manslaughter' },
    { value: '121', label: 'Rape' },
    { value: '122', label: 'Attempted Rape' },
    { value: '815', label: 'Sexual Penetration w/ Foreign Object' },
    { value: '820', label: 'Oral Copulation' },
    { value: '821', label: 'Sodomy' },
    { value: '210', label: 'Robbery' },
    { value: '220', label: 'Robbery - attempted' },
    { value: '230', label: 'ADW' },
    { value: '231', label: 'ADW against LAPD Police Officer' },
    { value: '235', label: 'Child beating' },
    { value: '236', label: 'Spousal beating (DV)' },
    { value: '250', label: 'Shots Fired' },
    { value: '251', label: 'Shots fired inhabited dwelling' },
    { value: '761', label: 'Brandishing' },
    { value: '926', label: 'Train Wrecking' },
    { value: '435', label: 'Lynching' },
    { value: '436', label: 'Lynching - attempted (Not Incl. in Part I Violent Crime)' },
    { value: '437', label: 'Resisting Arrest' },
    { value: '622', label: 'Battery on Firefighter' },
    { value: '623', label: 'Battery on Police Officer' },
    { value: '624', label: 'Battery - misdemeanor' },
    { value: '625', label: 'Other Misd. Assault' },
    { value: '626', label: 'Spousal/Cohab Abuse - Simple Assault (DV)' },
    { value: '627', label: 'Child Abuse - Simple Assault' },
    { value: '647', label: 'Throwing substance at vehicle' },
    { value: '763', label: 'Stalking' },
    { value: '928', label: 'Threatening Phone Calls / Letters' },
    { value: '930', label: 'Criminal Threats' },
    { value: '310', label: 'Burglary' },
    { value: '320', label: 'Burglary - attempted' },
    { value: '510', label: 'Stolen Vehicle (MVT / GTA)' },
    { value: '520', label: 'Stolen Vehicle - attempted' },
    { value: '433', label: 'DWOC' },
    { value: '330', label: 'Burg from Vehicle (BTFV)' },
    { value: '331', label: 'Theft from vehicle - $950.01 & over' },
    { value: '410', label: 'Burg from Vehicle - attempted' },
    { value: '420', label: 'Theft from vehicle - $950 & under' },
    { value: '421', label: 'Theft from vehicle attempted' },
    { value: '350', label: 'Theft from person' },
    { value: '351', label: 'Pursesnatch' },
    { value: '352', label: 'Pickpocket' },
    { value: '353', label: 'Drunkroll' },
]  

export default crimeTypeOptions;
